### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Nkeramov**
updated to nifi 1.20.0, some refactored, added more logging

### CODE REVIEW

**Comment by Nkeramov** [comment]
please revert this pull request, because it was made wrong

**Comment by david-streamlio** [comment]
Are you planning on resubmitting these changes in a different PR?

**Comment by Nkeramov** [comment]
No, because as I see it, you have already made most of the changes. I will update my copy of the repository. And then I will make a separate request with significant changes

**Comment by david-streamlio** [comment]
Ok, I have finished making changes to the repo for a bit. Looking forward to your PR.

**Pull request closed without merging**
